version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=development_test
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: sh -c "celery -A development_test worker -l info &&
                    celery -A development_test beat -l info"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
