# Generated by Django 3.2.5 on 2021-09-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('price', models.CharField(max_length=150)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores_app.store')),
            ],
        ),
    ]
